### ISSUE TITLE
handling one-to-many binomial matches

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/ausflora#28]
not sure what we want to do there

**Comment by wcornwell** [comment]
the issue is https://github.com/traitecoevo/ausflora/blob/2135e6c97be264227049afbbc4773681614b02ee/R/clean_names.R#L661

I'm a bit worried that we're not handling specific edge cases (e.g. splits) well here

@dfalster @ehwenk i don't want to diverge from what's happening in the austraits workflow, but i can't quite figure out if this is the same or if we need something more complicated there.

**Comment by dfalster** [comment]
We'll need to review this one with @ehwenk in August!

**Comment by wcornwell** [comment]
Seems like the `proParte` column in APC will be useful here: https://en.wiktionary.org/wiki/pro_parte

**Comment by wcornwell** [comment]
some names for testing purposes: <img width="610" alt="Screenshot 2023-07-11 at 10 48 45 am" src="https://github.com/traitecoevo/ausflora/assets/5534161/428d5004-e094-43c6-90ad-cd6511dab651">

**Comment by wcornwell** [comment]
I did some reading on this last night, and I think iNaturalist and eBird use a date based processing, where before and after the split is processed differently.  to be discussed when @ehwenk is back

**Comment by wcornwell** [comment]
this was easier than i thought, may be done here: https://github.com/traitecoevo/ausflora/tree/Handling-Splits

**Comment by wcornwell** [comment]
done via 6380c45b75f8b40b483aedc085221427af543ee9 (for now at least)
