### ISSUE TITLE
Error in taxonomic lookup function

### ISSUE THREAD

**Issue by seandres11** [traitecoevo/ausflora#29]
Hello!

I am trying to use this package and have run into a strange error. 

**I downloaded the two packages (ausflora and dtastorr) from github and ran the following code in one of the examples:** 

create_taxonomic_update_lookup(c("Banksia integrifolia","Acacia longifolia","Commersonia rosea"),full=FALSE)

**The code yields the following error message which I think has something to do with a bug in the APC dataset:** 

trying URL 'https://github.com/traitecoevo/ausflora/releases/download/0.0.2.9000/apc.parquet'
Content type 'application/octet-stream' length 10895737 bytes (10.4 MB)
downloaded 10.4 MB

Error: IOError: Couldn't deserialize thrift: TProtocolException: Invalid data

Please let me know if this is the case, and if so when it might be fixed. 

The R version I am using is 
R version 4.3.0

Cheers,
Sam

**Comment by dfalster** [comment]
Hi! Thanks for your interest. 

We're in the middle of reorganising this package. It will be ready for broader usage in a couple of months. 

In the meantime, very interested to hear about your intended use case!

Daniel

**Comment by wcornwell** [comment]
Thanks @seandres11 .  i think @yangsophieee fixed it, but hard to confirm on mac.  closing for now.

**Comment by wcornwell** [comment]
for future reference here is the root of the issue: 
```
The choice of binary transfer (mode = "wb" or "ab") is important on Windows, since unlike Unix-alikes it does distinguish between text and binary files and for text transfers changes \n line endings to \r\n (aka 'CRLF').

On Windows, if mode is not supplied (missing()) and url ends in one of .gz, .bz2, .xz, .tgz, .zip, .jar, .rda, .rds or .RData, mode = "wb" is set so that a binary transfer is done to help unwary users.

Code written to download binary files must use mode = "wb" (or "ab"), but the problems incurred by a text transfer will only be seen on Windows.
```
