### ISSUE TITLE
pkgdown website and expanding documentation

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/ausflora#65]
Will work on `website` branch for this! 

- Create pkgdown website
- Include workflow diagrams in vignette
- Prerender vignette to speed up `loading resources`
- Tidy up output `print(n = 6)` in vignette 
- Improve README (Best to point to pkgdown tutorials) 
- More detail on APC, APNI (difference between them) 
    - https://ibis-cloud.atlassian.net/wiki/spaces/NP/pages/1154383919/NSL+Name+export+format

**Comment by wcornwell** [comment]
pkgdown should be done? or did you want to add functionality?

**Comment by fontikar** [comment]
Ah sorry I wasn't clear! 
Thanks for making the structure @wcornwell :) I will here to make it 'nicer' with customising and internal linking!

**Comment by fontikar** [comment]
Leaving a paper trail for me

Including figures in articles is handled differently by rmarkdown 

- [documentation](https://pkgdown.r-lib.org/reference/build_articles.html#get-started) doesn't go a great job explaining
- https://github.com/r-lib/pkgdown/issues/1620

Solution is to put figure in articles folder instead of man/figures (which is used for vignette and README). Using this method, [rmarkdown::find_external_resources()](https://pkgs.rstudio.com/rmarkdown/reference/find_external_resources.html) can run successfully and detect the image

**Comment by fontikar** [comment]
All done here! Merged into master [eb95d0f](https://github.com/traitecoevo/ausflora/commit/eb95d0f86766f5f8eea4525ee8c86c674d3ee251)
