### ISSUE TITLE
Should "taxonomic_resources" be unloaded from the global environment when finished?

### ISSUE THREAD

**Issue by rubysaltbush** [traitecoevo/ausflora#7]
The `update_taxonomy` function loads a large list of 6 variables into the global environment while it's running. Is it possible to unload this `taxonomic_resources` list when the function finishes if it's no longer needed?

**Comment by dfalster** [comment]
Good question.  This resource is also loaded by `align_taxa`, unless you've run it before and cached the results in a file.  Quite a few people would not approve of saving something into the global environment like this. 

My thinking here is that the resources are slow to load, so, assuming you'll load them several times, this will get annoying and it will therefore be helpful to save them. This is only worth it if indeed you will load several times. This would occur if (for example) 

- you run both functions, ie. `align_taxa` and then `update_taxonomy`, as each uses the resources
- you run `align_taxa` a few times, e.g. when figuring out difficult species., with some manual corrections after the first run.

Some options are

1. Leave as is, with instructions on how to remove it at the end
2. Make saving in global environment optional
3. Figure out some way to make loading faster so repeated loading isn't an issue. E.g.Does it help to save the object as an rds?

**Comment by rubysaltbush** [comment]
Yes true. You're right r.e. `align_taxa`, I hadn't noticed it loading for this as I'm re-running a script and taxonomic_updates.csv is already cached.

I've just added ` rm(taxonomic_resources)` to my script at the end of all apcnames functions for now, maybe adding this to the end of `example.R` is a simple workaround for now?

**Comment by wcornwell** [comment]
If we want to go to CRAN, they are going to not be happy with the global environment thing.  So this is worth discussing.

**Comment by dfalster** [comment]
For sure. This was introduced because loading is non trivial. The simplest option is to simply pass in the data object into the function. It's just more typing.

**Comment by wcornwell** [comment]
fixed by #41
